name:                aoc2020
version:             0.1.0.0
github:              ewilden/aoc2020
license:             BSD3
author:              Evan Wildenhain
maintainer:          evan.wildenhain@gmail.com
copyright:           2020 Evan Wildenhain

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ewilden/aoc2020#readme>

dependencies:
- arithmoi == 0.9.0.0
- base >= 4.11 && < 10
- barbies >= 2.0.2.0
- bimap
- composition
- containers
- megaparsec
- microlens
- microlens-platform
- monoidal-containers
- mtl
- parser-combinators
- rio >= 0.1.12.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  aoc2020-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - aoc2020
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  aoc2020-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - aoc2020
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
